/*
 *  Copyright 2009 Utkin Dmitry
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/* 
 *  This file is part of the WSF Staff project.
 *  Please, visit http://code.google.com/p/staff for more information.
 */

// This file generated by staff_codegen
// DO NOT EDIT

#ifndef _$(Interface.Name)Proxy_h_
#define _$(Interface.Name)Proxy_h_

#include <staff/common/WsdlTypes.h>
#include "$(Interface.FileName)"

namespace staff { class CService; }

#foreach $(Interface.Classes)
$(Class.OpeningNs)
class $(Class.Name)Proxy: public $(Class.Name)
{
public:
  $(Class.Name)Proxy(staff::CService* pService, const rise::CString& sID);
  void SetService(staff::CService* pService);
#foreach $(Class.Members)
  $(Member.Return) $(Member.Name)($(Member.Params))$(Member.Const);
#end

private:
  mutable staff::CService* m_pService;
  const rise::CString m_sID;
};
$(Class.EndingNs)

#end
#endif
