// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// Service Implementation

#ifndef _IssuerImpl_h_
#define _IssuerImpl_h_

#include <map>
#include "Issuer.h"

namespace samples
{
namespace sharedtypes
{

  //! implementation of Issuer
  class IssuerImpl: public Issuer
  {
  public:
    IssuerImpl();
    virtual ~IssuerImpl();
    virtual ticket::Ticket Issue(const std::string& sOwner);
    virtual bool WasIssued(const ticket::Ticket& stTicket);
    virtual ticket::TicketsList GetAllTickets() const;

  private:
    typedef std::map<int, ticket::Ticket> TicketMap;

  private:
    int m_nLastIssuedId;
    TicketMap m_mIssuedTickets;
  };
}
}


#endif // _IssuerImpl_h_

