// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// DO NOT EDIT

#ifndef _SERVICEFACTORY_H_
#define _SERVICEFACTORY_H_

#include <typeinfo>
#include <string>

namespace staff
{
  class IService;

  //! service factory
  class CServiceFactory
  {
  public:
    //!         get instance of service factory
    static CServiceFactory& Inst();

    //!         free instance of service factory
    static void FreeInst();

    //!         allocate new object for work with service
    /*! examples:
        rise::CSharedPtr<CCalculator> pCalculator = staff::CServiceFactory::Inst().GetService<CCalculator>("http://localhost:9090/axis2/services/Calculator");
        rise::CSharedPtr<CCalculator> pCalculator = staff::CServiceFactory::Inst().GetService<CCalculator>("", "", "mycalc");

        \param  sServiceUri - service URI
        \param  sSessionId - session identifier
        \return pointer to object for work with service
        */
    template<typename TServiceClientBaseType>
    TServiceClientBaseType* GetService(const std::string& sServiceUri = "",
                                       const std::string& sSessionId = "",
                                       const std::string& sInstanceId = "")
    {
      return static_cast<TServiceClientBaseType*>(AllocateClient(typeid(TServiceClientBaseType).name(),
                                                                      sServiceUri, sSessionId, sInstanceId));
    }

  private:
    //! private constructor
    CServiceFactory();

    staff::IService* AllocateClient(const std::string& sClientType, const std::string& sServiceUri,
                             const std::string& sSessionId, const std::string& sInstanceId);

  private:
    static CServiceFactory* m_pInst;  //!< instance
  };
}

#endif // _SERVICEFACTORY_H_
