// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// DO NOT EDIT

#include <rise/plugin/PluginExport.h>
#include <rise/common/MutablePtr.h>
#foreach $(Project.Interfaces)
#include "$(Interface.Name)Wrapper.h"
#end
#include "ComponentImpl.h"

RISE_DECLARE_PLUGIN($(Project.Interfaces.Interface.Classes.Class.Namespace)CComponentImpl)

$(Project.Interfaces.Interface.Classes.Class.OpeningNs)
  CComponentImpl::CComponentImpl()
  {
#foreach $(Project.Interfaces)
#foreach $(Interface.Classes)
    m_mServices["$(Class.ServiceNsName)"] = new $(Class.NsName)Wrapper(this);
#end
#end
  }

  CComponentImpl::~CComponentImpl()
  {
  }

  const rise::CString& CComponentImpl::GetName() const
  {
    return m_sName;
  }

  const staff::CService* CComponentImpl::GetService( const rise::CString& sService ) const
  {
    staff::TServiceMap::const_iterator itService = m_mServices.find(sService);
    if (itService == m_mServices.end())
      return NULL;

    return itService->second;
  }

  staff::CService* CComponentImpl::GetService( const rise::CString& sService )
  {
    staff::TServiceMap::iterator itService = m_mServices.find(sService);
    if (itService == m_mServices.end())
      return NULL;

    return itService->second;
  }

  const staff::TServiceMap& CComponentImpl::GetServices() const
  {
    return m_mServices;
  }

  const rise::CString CComponentImpl::m_sName = "$(Project.Interfaces.Interface.Classes.Class.ComponentName)";

$(Project.Interfaces.Interface.Classes.Class.EndingNs)
