// This file generated by staff_codegen
// Service Implementation

#ifndef _ObjectAdminImpl_h_
#define _ObjectAdminImpl_h_

#include "ObjectAdmin.h"

namespace staff
{
  namespace admin
  {
    class CObjectAdminImpl: public CObjectAdmin
    {
    public:
      CObjectAdminImpl();
      virtual ~CObjectAdminImpl();

      virtual ::staff::admin::TObjectIdList GetObjectIdList();
      virtual ::staff::admin::TObjectIdList GetObjectIdListWithParent(int nParentId);
      virtual ::staff::admin::SObject GetObjectById(int nObjectId);
      virtual ::staff::admin::TObjectList GetObjectList(const ::staff::admin::TObjectIdList& rlsObjectIdList);
      virtual int AddObject(const ::staff::admin::SObject& rstObject);
      virtual void RemoveObject(int nObjectId);
      virtual void ReplaceObject(const ::staff::admin::SObject& rstObject);

      virtual ::staff::admin::TObjectTypesList GetObjectTypeList();
      virtual int AddObjectType(const ::staff::admin::SObjectType& rstObjectType);
      virtual void ReplaceObjectType(const ::staff::admin::SObjectType& rstObjectType);
      virtual void RemoveObjectType(int nObjectTypeId);
    };
  }
}


#endif // _ObjectAdminImpl_h_
