// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// Service Implementation

#ifndef _ObjectAdminImpl_h_
#define _ObjectAdminImpl_h_

#include "ObjectAdmin.h"

namespace staff
{
namespace admin
{

  class CObjectAdminImpl: public CObjectAdmin
  {
  public:
    CObjectAdminImpl();
    virtual ~CObjectAdminImpl();
    virtual ::staff::admin::SObject GetById(int nId);
    virtual ::staff::admin::SObject GetByPathName(const std::string& sPathName);
    virtual ::staff::admin::TObjectList GetChilds(int nId);
    virtual int Add(const ::staff::admin::SObject& rstObject);
    virtual void Remove(int nObjectId);
    virtual void SetDescription(int nObjectId, const std::string& sDescription);
  };
}
}


#endif // _ObjectAdminImpl_h_
