#!/bin/sh

DISTRIB=../staff_tmp$(printf %x $(date +%s))/
REVISION=$(LANG=en svn info --non-interactive 2>&- | grep 'Revision: ' | cut -d' ' -f2)
TARBALLNAME=../staff-r${REVISION}.tar.bz2

test -z "$(svn st | wc -l)" || echo "\033[1mWARNING: working copy was locally modified\033[0m"

echo "creating tarball..."

rm -Rf ${DISTRIB}
mkdir -p ${DISTRIB}staff/
cp -Rf . ${DISTRIB}staff/
cd ${DISTRIB}staff/

find -type d -name .svn | xargs rm -Rf
make clean >/dev/null && make distclean >/dev/null
cd ..

tar c staff | bzip2 >${TARBALLNAME}
rm -Rf ${DISTRIB}

echo "created ${TARBALLNAME}"
