// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/

#ifndef _test_h_
#define _test_h_

#include <staff/common/Optional.h>
#include <staff/common/WsdlTypes.h>
#include <staff/common/IService.h>


  // *baseType: token
  enum testEnum
  {
    testEnum1,
    testEnum2
  };

  class Test171: public staff::IService
  {
  public:
    // *param-testEnum-isAttribute: true
    // *param-testEnum-useParentElement: true
    virtual void test( ::testEnum testEnum) = 0;
  };


#endif // _test_h_

