// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/

#ifndef _STAFF_TEST_TEST135_H_
#define _STAFF_TEST_TEST135_H_

#include <staff/common/IService.h>

// *ignoreBegin
template <typename Type> 
class test
{
};
// *ignoreEnd


namespace staff
{
namespace test
{

  struct Struct1
  {
    // *ignoreBegin
    mutable int i;
    // *ignoreEnd
    int a;
  };

  //! Test135 service
  class Test135: public staff::IService
  {
  public:
    // *ignoreBegin
    template <typename Type> class test {};
    // *ignoreEnd
  };

}
}

#endif // _STAFF_TEST_TEST135_H_

