.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH staff 1 "2011"

.SH NAME
staff \- Web Service Framework for C++.

.SH DESCRIPTION
Staff is Web Service Framework for C++ based on Apache Axis2/C. WSF Staff provide C++ interface to most used Apache Axis2/C functions, and also it provide many additional features. 

.SH FEATURES

Main features provided by WSF Staff:
.RS
.B -
stateful Web Services implementation in C++ with instance support;
.RE
.RS
.B -
synchronous and asynchronous client implementation in C++, AJAX and J2ME;
.RE
.RS
.B -
service-component architecture implementation;
.RE
.RS
.B -
to interact with the service you can use: simple types (number, string, enum, ...), complex types (struct, typedef, list, ...) and raw xml (DataObject);
.RE
.RS
.B -
support for RESTful web services and clients;
.RE
.RS
.B -
WSDL support with xsd import/export;
.RE
.RS
.B -
J2ME client support is based on ksoap;
.RE
.RS
.B -
code generator to generate any sort of Web Services related source code (not only in C++);
.RE
.RS
.B -
access to relational databases via DAS (data access service). Supported DBMS are: Postgresql, MySQL, SQLite3.;
.RE
.RS
.B -
traffic compression support in J2ME and AJAX.
.RE
.RS
.B -
security support (users, groups, sessions, ACLs, etc.);
.RE

For more information visit: http://code.google.com/p/staff/wiki/StaffDetails

.SH LINKS
.B Project's page:
http://code.google.com/p/staff
.RE
.B Wiki documentation:
http://code.google.com/p/staff/wiki/Welcome
.RE
.B Examples:
http://code.google.com/p/staff/wiki/Examples
.RE
.B Support page:
http://code.google.com/p/staff/wiki/SupportPage
.RE
