// This file generated by staff_codegen
// DO NOT EDIT

#ifndef _COMPONENTIMPL_H_
#define _COMPONENTIMPL_H_

#include <staff/component/Component.h>

$(Project.Interfaces.Interface.Classes.Class.OpeningNs)
  //!  ComponentImpl
  class CComponentImpl: public staff::CComponent
  {
  public:
    //!        конструктор по умолчанию
    CComponentImpl();

    //!        деструктор
    virtual ~CComponentImpl();

    //!         получить имя компонента
    /*! \return имя компонента
    */
    const rise::CString& GetName() const;

    //!         получить сервис
    /*! \param  sService - имя сервиса
        \return указатель на обьект для работы с сервисом, NULL если сервис не найден
        */
    const staff::CService* GetService(const rise::CString& sService) const;

    //!         получить сервис
    /*! \param  sService - имя сервиса
        \return указатель на обьект для работы с сервисом, NULL если сервис не найден
        */
    staff::CService* GetService(const rise::CString& sService);

    //!         получить список сервисов
    /*! \return список сервисов
    */
    const staff::TServiceMap& GetServices() const;

  private:
    staff::TServiceMap m_mServices;
    static const rise::CString m_sName;
  };
$(Project.Interfaces.Interface.Classes.Class.EndingNs)

#endif // _COMPONENTIMPL_H_
