# environment file for make

PLATFORM := $(shell uname -m)
ifeq ($(shell uname -o 2>/dev/null),Msys)
  OS := MINGW
else
  OS := $(shell uname -s)
endif

SRCDIR = src/
OBJDIR = obj/$(PLATFORM)/
OUTDIR = out/$(PLATFORM)/
BINDIR = bin/
LIBDIR = lib/

COMPILER_FLAGS =
LINKER_FLAGS =

ifeq ($(PLATFORM),x86_64)
  COMPILER_FLAGS += -D_M_X64
endif

ifneq ($(DEBUG),)
  COMPILER_FLAGS += -D_DEBUG -g -O0
  LINKER_FLAGS += -g -O0
endif

COMPILER_WARNING_FLAGS = -Wall -W -pedantic -Wno-long-long
COMPILER_FLAGS += -DOS_$(OS)=1 -D_REENTRANT $(COMPILER_WARNING_FLAGS)

ifeq ($(OS),Linux)
  LINUX_VERSION := $(shell find /etc/ -maxdepth 1 -regex '.*[-_]version' -printf '%f\n' | sed -e 's/\([^-_]*\).*/\1/gm' -e 's/[^a-zA-Z0-9_]/_/gm')
  LINUX_RELEASE := $(shell find /etc/ -maxdepth 1 -regex '.*[-_]release' -printf '%f\n' | sed -e 's/\([^-_]*\).*/\1/gm' -e 's/[^a-zA-Z0-9_]/_/gm')
ifneq ($(LINUX_VERSION),)
  COMPILER_FLAGS += -DLINUX_VERSION_$(LINUX_VERSION)=1
endif
ifneq ($(LINUX_RELEASE),)
  COMPILER_FLAGS += -DLINUX_RELEASE_$(LINUX_RELEASE)=1
endif
endif

VPATH = $(SRCDIR)

CFLAGS += $(COMPILER_FLAGS)
LFLAGS += $(LINKER_FLAGS)
CXXFLAGS += $(COMPILER_FLAGS)
LDFLAGS += $(LINKER_FLAGS)

ECHO := echo$(shell test $$(readlink /bin/sh) = "dash" || echo ' -e ')

ifneq ($(VERSION),)
  DVERSION = .$(VERSION)
endif

ifeq ($(OS),Darwin)
  LIBPREFIX = lib
  LIBEXT = .dylib
  LIBVEREXT = $(DVERSION)$(LIBEXT)
  LDLIB = -dynamiclib -Wl,-dylib_install_name -Wl,
  LIBRARY_PATH_ENV = DYLD_LIBRARY_PATH
else
ifeq ($(OS),MINGW)
  LIBPREFIX = 
  LIBEXT = .dll
  LIBVEREXT = $(LIBEXT)
  LDLIB = -shared -Wl,-soname,
  CC = gcc
  LIBRARY_PATH_ENV = PATH
else
  LIBPREFIX = lib
  LIBEXT = .so
  LIBVEREXT = $(LIBEXT)$(DVERSION)
  LDLIB = -shared -Wl,-soname,
  LIBRARY_PATH_ENV = LD_LIBRARY_PATH
endif
endif

ifeq ($(LINUX_RELEASE),MCBC)
APXS := $(shell which /www/bin/apxs 2>/dev/null)
else
APXS := $(shell which apxs apxs2 2>/dev/null)
ifneq ($(APXS),)
APXSREAL := $(shell readlink $(APXS))
ifneq ($(APXSREAL),)
APXS := $(APXSREAL)
endif
endif
endif
