// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// Service Implementation

#ifndef _DepSvc2Impl_h_
#define _DepSvc2Impl_h_

#include "DepSvc2.h"

namespace samples
{
namespace loadorder
{

  //! implementation of DepSvc2 service
  class DepSvc2Impl: public DepSvc2
  {
  public:
    DepSvc2Impl();
    virtual ~DepSvc2Impl();
    virtual void OnCreate();
    virtual void OnDestroy();
  };
}
}


#endif // _DepSvc2Impl_h_
