// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// Service Implementation

#include "NillableServiceImpl.h"

namespace samples
{
namespace nillable
{

NillableServiceImpl::NillableServiceImpl()
{
}

NillableServiceImpl::~NillableServiceImpl()
{
}

void NillableServiceImpl::OnCreate()
{
  // this function is called when service instance is created and registered
}

void NillableServiceImpl::OnDestroy()
{
  // this function is called immediately before service instance destruction
}

void NillableServiceImpl::Set(const Info& rInfo)
{
  m_tInfo = rInfo;
}

Info NillableServiceImpl::Get()
{
  return m_tInfo;
}

void NillableServiceImpl::SetNillableStruct(const staff::Nillable<Info>& rInfo)
{
  m_tNillableInfo = rInfo;
}

staff::Nillable<Info> NillableServiceImpl::GetNillableStruct()
{
  return m_tNillableInfo;
}

staff::Nillable<int> NillableServiceImpl::GetNillableInt()
{
  return m_tNillableInt;
}

void NillableServiceImpl::SetNillableInt(const staff::Nillable<int>& rNillableInt)
{
  m_tNillableInt = rNillableInt;
}


}
}

