// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// DO NOT EDIT

#ifndef _COMPONENTIMPL_H_
#define _COMPONENTIMPL_H_

#include <staff/component/Component.h>

$(Project.Interfaces.Interface.Classes.Class.OpeningNs)
  //!  Component implementation
  class CComponentImpl: public staff::CComponent
  {
  public:
    //!        default constructor
    CComponentImpl();

    //!        destructor
    virtual ~CComponentImpl();

    //!         get component name
    /*! \return component name
    */
    const rise::CString& GetName() const;

    //!         get service
    /*! \param  sService - service name
        \return pointer to work with service, NULL if no service found
        */
    const staff::CService* GetService(const rise::CString& sService) const;

    //!         get service
    /*! \param  sService - service name
        \return pointer to work with service, NULL if no service found
        */
    staff::CService* GetService(const rise::CString& sService);

    //!         get services map
    /*! \return services map
    */
    const staff::TServiceMap& GetServices() const;

  private:
    staff::TServiceMap m_mServices;
    static const rise::CString m_sName;
  };
$(Project.Interfaces.Interface.Classes.Class.EndingNs)

#endif // _COMPONENTIMPL_H_
