# environment file for make

#set default target 'make', if not set
ifeq ($(MAKECMDGOALS),)
  MAKECMDGOALS = make
all: make
endif

TOPDIR := $(realpath $(dir $(lastword $(MAKEFILE_LIST)))/..)/
ifeq ($(MAKEFILE_ENV_INCLUDED),)
include $(TOPDIR)Makefile.env
endif

check:
ifeq ($(TOPDIR),)
	@echo "\033[31;1mERROR: Can't detect topdir! \nPlease, rename topdir to \"staff\" or make, using command: TOPDIR=<full path to staff> make\033[0m"; false
else
ifeq ($(STAFF_HOME),)
ifeq ($(MAKECMDGOALS),install)
	@echo "\033[31;1mERROR: STAFF_HOME is not set\033[0m"; false
endif
endif
endif

INCDIR = include/staff/das/$(TARGET)/
COMDIR = components/
SAMPLESDIR = samples/

STAFF_DEPLOY_HOME := $(TOPDIR)deploy/$(PLATFORM)$(STAFF_HOME)

CXXFLAGS += -I$(STAFF_DEPLOY_HOME)/include
LDFLAGS += -L$(STAFF_DEPLOY_HOME)/lib

CXXFLAGS += -I$(DEPLOYDIR)include
LDFLAGS += -L$(DEPLOYDIR)lib

VPATH = $(SRCDIR)

DEPLOYROOTDIR = $(TOPDIR)deploy/$(PLATFORM)/
DEPLOYDIR = $(DEPLOYROOTDIR)$(STAFF_HOME)/
INSTALLDIR = $(STAFF_HOME)/

LIBTARGETVER = $(LIBPREFIX)staff$(TARGET)$(LIBVEREXT)
LIBTARGET = $(LIBPREFIX)staff$(TARGET)$(LIBEXT)

STAFF_CODEGEN = STAFF_HOME=$(DEPLOYDIR) $(LIBRARY_PATH_ENV)=$(DEPLOYDIR)lib:$$$(LIBRARY_PATH_ENV) $(DEPLOYDIR)bin/staff_codegen

