// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// Client skeleton

#include <memory>
#include <rise/common/Log.h>
#include <staff/common/Exception.h>
#include <staff/client/ServiceFactory.h>
#include "Echo.h"

// callbacks


int main(int nArgs, const char* paszArgs[])
{
  try
  {
    std::auto_ptr< Echo > pEcho(::staff::CServiceFactory::Inst().GetService< Echo >());

    RISE_ASSERTS(pEcho.get(), "Cannot get client for service samples.Echo!");

    // Invoke Your service here:

    std::string tEchoStringResult = pEcho->EchoString("Hello World!");
    rise::LogInfo() << "EchoString result: " << tEchoStringResult;
  }
  RISE_CATCH_ALL

  return 0;
}

