// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// Client skeleton

#include <iostream>
#include <memory>
#include <staff/utils/Log.h>
#include <staff/common/DataObject.h>
#include <staff/common/logoperators.h>
#include <staff/common/Exception.h>
#include <staff/client/ServiceFactory.h>
#include "foo.h"
#include "fooXsd.h"
#include "fooXsdProxy.h"
#include "fooCommon.h"
#include "fooCommonProxy.h"

using namespace staff;

int main(int /*nArgs*/, const char* /*paszArgs*/[])
{
  try
  {
      std::string attr1Namespace;
      ::fooRequest fooRequest;
      staff::DataObject dataObject1("staff-packet");
      staff::DataObject dataObject2("staff-packet");

      fooRequest.fooRequest.attr1 = "value";

      dataObject1<< fooRequest.fooRequest;

      dataObject2 =  dataObject1.FirstChild();

      attr1Namespace = dataObject2.GetNamespaceUri();

      STAFF_ASSERT(attr1Namespace == "http://ns/v1", "Wrong namespace for attr1");

      //Normal exit (assert succeded)
      return 0;
  }
  STAFF_CATCH_ALL_DESCR("TEST FAILED")

  //Abnormal exit, exception thrown
//  return 3;
  return 0;
}

