// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// Service Implementation

#ifndef _SoapArrayServiceImpl_h_
#define _SoapArrayServiceImpl_h_

#include "SoapArrayService.h"

namespace samples
{
namespace soaparray
{

  //! implementation of service to demonstrate SOAP Array support
  class SoapArrayServiceImpl: public SoapArrayService
  {
  public:
    SoapArrayServiceImpl();
    virtual ~SoapArrayServiceImpl();
    virtual void OnCreate();
    virtual void OnDestroy();
    virtual void SetIntArray(const staff::Array<int>& rArray);
    virtual staff::Array<int> GetIntArray() const;
    virtual staff::Array<int> GetSparseIntArray() const;
    virtual void SetData(const Data& rData);
    virtual Data GetData() const;
    virtual Data GetSparseData() const;
    virtual void SetDataArray(const ::samples::soaparray::DataArray& rDataArray);
    virtual ::samples::soaparray::DataArray GetDataArray() const;
    virtual void SetArrayOfIntArray(const ::samples::soaparray::ArrayOfIntArray& rArrayOfIntArray);
    virtual ::samples::soaparray::ArrayOfIntArray GetArrayOfIntArray() const;
    virtual ::samples::soaparray::ArrayOfIntArray GetSparseArrayOfIntArray() const;
    virtual void SetArrayOfDataArray(const ::samples::soaparray::ArrayOfDataArray& rArrayOfDataArray);
    virtual ::samples::soaparray::ArrayOfDataArray GetArrayOfDataArray() const;
    virtual void SetArrayOfArrayOfIntArray(const ::samples::soaparray::ArrayOfArrayOfIntArray& rArrayOfArrayOfIntArray);
    virtual ::samples::soaparray::ArrayOfArrayOfIntArray GetArrayOfArrayOfIntArray() const;
    virtual ::samples::soaparray::ArrayOfArrayOfIntArray GetSparseArrayOfArrayOfIntArray() const;
    virtual staff::Array<int> Get2dIntArray() const;
    virtual staff::Array<int> Get2dSparseIntArray() const;
    virtual staff::Array< staff::Array<int> > GetComplex2dIntArray() const;
    virtual staff::Array< staff::Array<int> > GetComplex2dSparseIntArray() const;
  };
}
}


#endif // _SoapArrayServiceImpl_h_
