// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// Client skeleton

#include <memory>
#include <staff/utils/Log.h>
#include <staff/common/Exception.h>
#include <staff/client/ServiceFactory.h>
#include "Echo.h"

int main(int /*nArgs*/, const char* /*paszArgs*/[])
{
  try
  {
    std::auto_ptr< ::samples::simple::Echo > pEcho(::staff::ServiceFactory::Inst().GetService< ::samples::simple::Echo >());

    STAFF_ASSERT(pEcho.get(), "Cannot get client for service samples.simple.Echo!");

    // Invoke Your service here:

    std::string tEchoStringResult = pEcho->EchoString("Hello world!");
    staff::LogInfo() << "EchoString result: " << tEchoStringResult;
  }
  STAFF_CATCH_ALL

  return 0;
}

