// This file generated by staff_codegen
// DO NOT EDIT

#ifndef _$(Interface.Name)Proxy_h_
#define _$(Interface.Name)Proxy_h_

#include <staff/client/Axis2Client.h>
#include "$(Interface.FileName)"

#ifneq("$(Interface.Namespace)","")
namespace $(Interface.Namespace)
{
#ifeqend
#foreach $(Interface.Classes)
class $(Class.Name)Proxy: public $(Class.Name)
{
public:
  $(Class.Name)Proxy();
  void Init(const rise::CString& sSessionId, const rise::CString& sServiceName, const rise::CString& sHostName, const rise::CString& sHostPort);
#foreach $(Class.Members)
  $(Member.Return) $(Member.Name)($(Member.Params))$(Member.Const);
#end
private:
  mutable staff::CAxis2Client m_tClient;
};

#end
#ifneq("$(Interface.Namespace)","")
}

#ifeqend
#endif
