// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// Client skeleton

#include <memory>
#include <rise/common/Log.h>
#include <rise/threading/Thread.h>
#include <staff/common/DataObject.h>
#include <staff/client/ICallback.h>
#include <staff/common/Exception.h>
#include <staff/client/ServiceFactory.h>
#include "Echo.h"

// callbacks
// callback for Echo::EchoString
class EchoEchoStringCallback: public staff::ICallback< const std::string& >
{
public:
  virtual void OnComplete(const std::string& tResult)
  {
    // process result here
    rise::LogInfo() << "EchoString(asynch) result: " << tResult;
  }

  void OnFault(const staff::CDataObject& rFault)
  {
    // process error here
    rise::LogError() << rFault.ToString();
  }
};



int main(int nArgs, const char* paszArgs[])
{
  try
  {
    std::auto_ptr< ::samples::Echo > pEcho1(::staff::CServiceFactory::Inst().GetService< ::samples::Echo >());
    std::auto_ptr< ::samples::Echo > pEcho2(::staff::CServiceFactory::Inst().GetService< ::samples::Echo >());

    RISE_ASSERTES(pEcho1.get(), rise::CLogicNoItemException, "Cannot get client for service samples.Echo!");
    RISE_ASSERTES(pEcho2.get(), rise::CLogicNoItemException, "Cannot get client for service samples.Echo!");

    // Invoke Your service here:
    EchoEchoStringCallback tEchoEchoStringCallback;
    pEcho1->EchoString("test1", tEchoEchoStringCallback);

    // using second client to call service while first client processing request
    std::string tEchoStringResult = pEcho2->EchoString("test2");
    rise::LogInfo() << "EchoString result: " << tEchoStringResult;

    // Wait for asynch call is completed
    while (!tEchoEchoStringCallback.IsCompleted())
    {
      rise::threading::CThread::Sleep(1000);
    }

  }
  catch(const staff::CRemoteException& rEx)
  {
    rise::LogError() << rEx.GetDescr();
  }
  RISE_CATCH_ALL

  return 0;
}

