// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// DO NOT EDIT

#ifndef _COMPONENTIMPL_H_
#define _COMPONENTIMPL_H_

#include <string>
#include <staff/component/Component.h>

$(Project.OpeningNs)
  //!  Component implementation
  class ComponentImpl: public staff::Component
  {
  public:
    //! default constructor
    ComponentImpl();

    //! destructor
    virtual ~ComponentImpl();

    //! get component name
    /*! \return component name
    */
    const std::string& GetName() const;

  private:
    static const std::string m_sName;
  };
$(Project.EndingNs)

#endif // _COMPONENTIMPL_H_
