// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// Service Implementation

#include <staff/utils/Log.h>
#include "DepSvc1Impl.h"

namespace samples
{
namespace loadorder
{

DepSvc1Impl::DepSvc1Impl()
{
}

DepSvc1Impl::~DepSvc1Impl()
{
}

void DepSvc1Impl::OnCreate()
{
  staff::LogInfo() << "Service 1 is loaded";
}

void DepSvc1Impl::OnDestroy()
{
  // this function is called immediately before service instance destruction
}


}
}

