// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// Service Implementation

#include <staff/utils/Log.h>
#include "DepSvc4Impl.h"

namespace samples
{
namespace loadorder
{

DepSvc4Impl::DepSvc4Impl()
{
}

DepSvc4Impl::~DepSvc4Impl()
{
}

void DepSvc4Impl::OnCreate()
{
  staff::LogInfo() << "Service 4 is loaded";
}

void DepSvc4Impl::OnDestroy()
{
  // this function is called immediately before service instance destruction
}


}
}

