/*
 *  Copyright 2009 Utkin Dmitry
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/* 
 *  This file is part of the WSF Staff project.
 *  Please, visit http://code.google.com/p/staff for more information.
 */

// This file generated by staff_codegen
// DO NOT EDIT

#ifndef _SERVICELOCATOR_H_
#define _SERVICELOCATOR_H_

#include <rise/string/String.h>

namespace staff
{
  //!  класс для получения обьекта для работы с сервисом по имени
  class CServiceLocator
  {
  public:
    //!         получить ссылку на обьект локатора
    /*! \return ссылка на обьект локатора
    */
    static CServiceLocator& Inst();
    
    //!         получить указатель на обьект для работы с сервисом
    /*! \param  sServiceName - имя сервиса
        \param  sID - идентификатор
        */
    void* LocateService(const rise::CString& sServiceName, const rise::CString& sID);

  protected:
    //!        конструктор по умолчанию
    CServiceLocator();
    
    //!        деструктор
    ~CServiceLocator();
  
  private:
    class CServiceLocatorImpl;
    CServiceLocatorImpl* m_pImpl;
    static CServiceLocator* m_pInst;
  };
}

#endif // _SERVICELOCATOR_H_
