// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// DO NOT EDIT

#ifndef _$(Interface.Name)Proxy_h_
#define _$(Interface.Name)Proxy_h_

#ifneq($(Interface.Classes.$Count),0)
#include <staff/client/ServiceClient.h>
#ifeqend
#include "$(Interface.FilePath)$(Interface.Name).h"
#foreach $(Interface.Includes)
#include "$(Include.FilePath)$(Include.Name)Proxy.h"
#end

#ifneq($(Interface.Classes.$Count),0)
namespace staff
{
  class ServiceWrapper;
}

#foreach $(Interface.Classes)
$(Class.OpeningNs)
//! Proxy for component service $(Class.ServiceNsName)
class $(Class.Name)Proxy: public $(Class.Name)
{
public:
  $(Class.Name)Proxy(const std::string& sSessionId, const std::string& sInstanceId);
  virtual ~$(Class.Name)Proxy();
#foreach $(Class.Members)
  $(Member.Return) $(Member.Name)($(Member.Params))$(Member.Const);
#end
  staff::ServiceWrapper& GetServiceWrapper() const;
private:
  mutable staff::ServiceWrapper* m_pWrapper;
};

$(Class.EndingNs)
#end
#ifeqend // serializators
#cginclude <common/Serialization.h>

#endif

