// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// Client skeleton

#include <memory>
#include <rise/common/Log.h>
#include <rise/threading/Thread.h>
#include <staff/common/DataObject.h>
#include <staff/client/ICallback.h>
#include <staff/common/Exception.h>
#include <staff/client/ServiceFactory.h>
#include "Echo.h"

// callbacks
// callback for Echo::EchoString
class EchoEchoStringCallback: public staff::ICallback< const std::string& >
{
public:
  virtual void OnComplete(const std::string& tResult)
  {
    // process result here
    rise::LogInfo() << "EchoString(asynch) result: " << tResult;
  }

  void OnFault(const staff::DataObject& rFault)
  {
    // process error here
    rise::LogError() << rFault.ToString();
  }
};



int main(int /*nArgs*/, const char* /*paszArgs*/[])
{
  try
  {
    std::auto_ptr< Echo > pEcho(::staff::ServiceFactory::Inst().GetService< Echo >());

    RISE_ASSERTS(pEcho.get(), "Cannot get client for service echo!");

    // Invoke Your service here:

     EchoEchoStringCallback tEchoEchoStringCallback;
     pEcho->EchoString("Hello World!", tEchoEchoStringCallback);

    // Wait for asynch call is completed
    // Please note, that you cannot call any operation of this client
    // until this asynchronous request is completed.
    // To call operation while request is processing, please use another copy of client.
    while (!tEchoEchoStringCallback.IsCompleted())
    {
      rise::threading::CThread::Sleep(1000);
    }

  }
  RISE_CATCH_ALL

  return 0;
}

