// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// DO NOT EDIT

#include <memory>
#include <map>
#include <rise/string/String.h>
#include <rise/common/MutablePtr.h>
#include "IProxyAllocator.h"
#include "ServiceFactory.h"

namespace staff
{
  class CServiceFactory::CServiceFactoryImpl
  {
  public:
    typedef std::map<std::string, IProxyAllocator*> TProxyAllocatorMap;

  public:
    TProxyAllocatorMap m_mProxyAllocators;
  };

  IService* CServiceFactory::AllocateClient(const std::string& sClientType,
                                            const std::string& sServiceUri,
                                            const std::string& sSessionId,
                                            const std::string& sInstanceId)
  {
    rise::LogDebug() << "trying to get ProxyAllocator: [" << sClientType << "]";
    CServiceFactoryImpl::TProxyAllocatorMap::const_iterator itProxyAllocator =
        m_pImpl->m_mProxyAllocators.find(sClientType);
    if (itProxyAllocator == m_pImpl->m_mProxyAllocators.end())
    {
      return NULL;
    }

    return itProxyAllocator->second->AllocateProxy(sServiceUri, sSessionId, sInstanceId);
  }

  IService* CServiceFactory::AllocateClientByHost(const std::string& sClientType,
                                          const std::string& sHost,
                                          int nPort,
                                          const std::string& sProtocol,
                                          const std::string& sServiceName,
                                          const std::string& sSessionId,
                                          const std::string& sInstanceId)
  {
    rise::LogDebug() << "trying to get ProxyAllocator: [" << sClientType << "]";
    CServiceFactoryImpl::TProxyAllocatorMap::const_iterator itProxyAllocator =
        m_pImpl->m_mProxyAllocators.find(sClientType);
    if (itProxyAllocator == m_pImpl->m_mProxyAllocators.end())
    {
      return NULL;
    }

    const std::string& sBaseUri = sProtocol + "://" + sHost + ":" + rise::ToStr(nPort) + "/axis2/services/";

    return itProxyAllocator->second->AllocateProxy(sBaseUri, sServiceName, sSessionId, sInstanceId);
  }

  CServiceFactory& CServiceFactory::Inst()
  {
    if (m_pInst == NULL)
    {
      m_pInst = new CServiceFactory;
    }

    return *m_pInst;
  }

  void CServiceFactory::RegisterProxyAllocator(const std::string& sProxyTypeId, IProxyAllocator& rProxyAllocator)
  {
    m_pImpl->m_mProxyAllocators[sProxyTypeId] = &rProxyAllocator;
    rise::LogDebug() << "Registered ProxyAllocator: [" << sProxyTypeId << "]";
  }

  CServiceFactory::CServiceFactory()
  {
    m_pImpl = new CServiceFactoryImpl;
  }

  CServiceFactory::~CServiceFactory()
  {
    delete m_pImpl;
  }

  CServiceFactory* CServiceFactory::m_pInst = NULL;
}

