// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/

#ifndef _TEST136_H_
#define _TEST136_H_

#include <staff/common/Optional.h>
#include "Test136Types.h"

struct SomeStruct
{
  // *isAttribute: true
  staff::Optional< ::SomeEnumType> SomeType;
};


#endif // _TEST136_H_

