// This file generated by staff_codegen
// DO NOT EDIT

#ifndef _$(Interface.Name)Wrapper_h_
#define _$(Interface.Name)Wrapper_h_

#include <staff/service/ServiceWrapper.h>

#ifneq("$(Interface.Namespace)","")
namespace $(Interface.Namespace)
{
#ifeqend
#foreach $(Interface.Classes)
  class $(Class.Name)Impl;

  class $(Class.Name)Wrapper: public staff::CServiceWrapper
  {
  public:
    $(Class.Name)Wrapper();
    virtual ~$(Class.Name)Wrapper();

    virtual void Invoke(staff::COperation& rOperation);

  protected:
    $(Class.Name)Impl& ServiceImpl();
  private:
    $(Class.Name)Impl* m_pServiceImpl;
  };

#end
#ifneq("$(Interface.Namespace)","")
}

#ifeqend
#endif // _$(Interface.Name)Wrapper_h_
