// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// Service Implementation

#ifndef _TasksImpl_h_
#define _TasksImpl_h_

#include "Tasks.h"

namespace samples
{
namespace optional
{

  //! implementation of Tasks service
  class TasksImpl: public Tasks
  {
  public:
    TasksImpl();
    virtual ~TasksImpl();
    virtual void OnCreate();
    virtual void OnDestroy();
    virtual int Add(const Task& rstTask);
    virtual void UpdateOwner(int nTaskId, const staff::Optional< int >& rtnOwnerId);
    virtual void UpdateAttachInfo(int nTaskId, const staff::Optional< AttachInfo >& rtnAttachInfo);
    virtual ::samples::optional::TasksList GetAllTasks() const;
    virtual staff::Optional<AttachInfo> GetAttachInfo(int nTaskId);
    virtual staff::Optional< std::list<std::string> > EchoOpt(const staff::Optional< std::list<std::string> >& opt);
    virtual std::list< staff::Optional<std::string> > EchoOpt2(const std::list< staff::Optional<std::string> >& opt);

  private:
    TasksList m_lsTasks;
  };
}
}


#endif // _TasksImpl_h_
