// This file generated by staff_codegen
// Service Implementation

#ifndef _WidgetManagerImpl_h_
#define _WidgetManagerImpl_h_

#include "WidgetManager.h"
#include <rise/xml/XMLDocument.h>

namespace widget
{
  class CWidgetManagerImpl: public CWidgetManager
  {
  public:
    CWidgetManagerImpl();
    virtual ~CWidgetManagerImpl();
    virtual void Open(const rise::CString& sWidgetDB);
    virtual void Close();
    virtual void Commit();
    virtual TWidgetClassList GetWidgetClassList();
    virtual TWidgetMap GetWidgetList() const;
    virtual int AddWidget(const SWidget& rWidget);
    virtual void DeleteWidget(int nWidgetID);
    virtual void AlterWidget(int nWidgetID, const SWidget& rWidget);

  private:  
    const std::string& GetSessionId();
    int GetUserId();
    
    const TWidgetClassList& GetWidgetClasses();

  private:
    TWidgetClassList m_lsWidgetClasses;
    TWidgetMap m_mWidgets;
    rise::xml::CXMLDocument m_tDoc;
    rise::xml::CXMLDocument m_tDocClasses;
    rise::CString m_sFileName;
    rise::CString m_sFileNameClasses;
    rise::CString m_sWidgetDB;
    std::string m_sSessionId;
    int m_nUserId;
  };
}


#endif // _WidgetManagerImpl_h_
