// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// Client skeleton

#include "Test136.h"

int main(int /*nArgs*/, const char* /*paszArgs*/[])
{
  return 0;
}

