// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/

#ifndef _TEST136TYPES_H_
#define _TEST136TYPES_H_

enum SomeEnumType
{
   Value1,
   Value2,
   Value3
};

#endif // _TEST136TYPES_H_

