<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
    targetNamespace="http://foons"
    xmlns="http://foons"
    xmlns:ns="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
</wsdl:definitions>

