// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// Client skeleton

#include <stdio.h>
#include <iostream>
#include <rise/threading/SharedPtr.h>
#include <rise/string/String.h>
#include <rise/common/Log.h>
#include <rise/common/ExceptionTemplate.h>
#include <rise/common/console.h>
#include <staff/common/Exception.h>
#include <staff/common/DataObject.h>
#include <staff/client/ServiceFactory.h>
#include "DataAccessService.h"

int main(int nArgs, const char* paszArgs[])
{
  try
  {
    {
      rise::CSharedPtr< ::staff::das::DataAccessService > pDataAccessService = 
        ::staff::CServiceFactory::Inst().GetService< ::staff::das::DataAccessService >();

      RISE_ASSERTES(pDataAccessService != NULL, rise::CLogicNoItemException, "Cannot get client for service staff.das.DataAccessService!");

      // Invoke Your service here:
      std::cout << "Providers: \n";
      ::staff::das::StringList lsProviders = pDataAccessService->GetProviders();
      for (::staff::das::StringList::const_iterator itProvider = lsProviders.begin();
          itProvider != lsProviders.end(); ++itProvider)
      {
        std::cout << "  - " << *itProvider << "\n";
      }


      std::cout << "DataSources: \n";
      ::staff::das::StringList lsDataSources = pDataAccessService->GetDataSources();
      for (::staff::das::StringList::const_iterator itDataSource = lsDataSources.begin();
          itDataSource != lsDataSources.end(); ++itDataSource)
      {
        std::cout << "  - " << *itDataSource << "\n";
      }

      pDataAccessService->SetDataSource("staff.das.samples.Users");
      staff::CDataObject tdoInterface = pDataAccessService->GetInterface();

      std::cout << "\n\n----------------------\n" << tdoInterface.ToString() << "\n------------------------\n\n";

      staff::CDataObject tdoRequest("GetAllUsers");
      staff::CDataObject tdoResult = pDataAccessService->Invoke(tdoRequest);

      std::cout << "\nRESULT:\n----------------------\n" << tdoResult.ToString() << "\n------------------------\n\n";

      pDataAccessService->FreeDataSource();
    }
  }
  catch(const staff::CRemoteException& rEx)
  {
    rise::LogError() << rEx.GetDescr();
  }
  RISE_CATCH_ALL
  
  return 0;
}
