// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// Service Implementation

#include "EchoImpl.h"

namespace samples
{
namespace simple
{

  std::string EchoImpl::EchoString(const std::string& sText)
  {
    return sText;
  }

}
}

