// This file generated by staff_codegen
// Service Implementation

#ifndef _CalcServiceImpl_h_
#define _CalcServiceImpl_h_

#include "CalcService.h"

namespace staff
{
  class CComponentConfig;
}

namespace calc
{
  class CCalcServiceImpl: public CCalcService
  {
  public:
    CCalcServiceImpl();
    virtual ~CCalcServiceImpl();
    virtual int Add(int nA, int nB) const;
    virtual int Sub(int nA, int nB) const;
    virtual void SetMem(int nMem);
    virtual int GetMem() const;

  protected:
    staff::CComponentConfig& GetConfig() const;
  private:
    mutable staff::CComponentConfig* m_pConfig;
  };
}


#endif // _CalcServiceImpl_h_
