/*
 *  Copyright 2009 Utkin Dmitry
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/* 
 *  This file is part of the WSF Staff project.
 *  Please, visit http://code.google.com/p/staff for more information.
 */

// This file generated by staff_codegen
// Service Implementation

#include <string>
#include <rise/common/Log.h>
#include <rise/common/ExceptionTemplate.h>
#include <rise/common/SharedPtr.h>
#include <rise/xml/XMLNode.h>
#include <staff/common/Config.h>
#include <staff/component/SharedContext.h>
#include <staff/component/ServiceWrapper.h>
#include <staff/component/ServiceInstanceManager.h>
#include <staff/component/ComponentConfig.h>
#include <staff/component/ComponentConfigManager.h>
#include "SubService.h"
#include "CalcServiceImpl.h"

namespace samples
{
  namespace calc
  {
    CCalcServiceImpl::CCalcServiceImpl():
      m_pConfig(NULL)
    {
    }

    CCalcServiceImpl::~CCalcServiceImpl()
    {
    }

    int CCalcServiceImpl::Add(int nA, int nB) const
    {
      return nA + nB;  // result
    }

    int CCalcServiceImpl::Sub(int nA, int nB) const
    {
      rise::CSharedPtr<CSubService> rpSubService =
        staff::CServiceInstanceManager::Inst().ServiceInstance(this, "samples.calc.SubService");

      RISE_ASSERTES(rpSubService, rise::CLogicNoItemException,
          "Cannot get service [samples.calc.SubService]");

      return rpSubService->Sub(nA, nB);
    }

    void CCalcServiceImpl::SetMem(int nMem)
    {
      m_pConfig->Config()["Mem"] = nMem;
    }

    int CCalcServiceImpl::GetMem() const
    {
      return m_pConfig->Config()["Mem"].AsInt();  // result
    }

    void CCalcServiceImpl::OnCreate()
    {
      m_pConfig = &staff::CComponentConfigManager::Inst().GetComponentConfig("samples.calc", "CalcService.xml", true);
      RISE_ASSERTS(m_pConfig, "Can't get config");
    }

    void CCalcServiceImpl::OnDestroy()
    {
      m_pConfig->SaveConfig();
    }
  }
}
