// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// Service Implementation

#ifndef _DepSvc1Impl_h_
#define _DepSvc1Impl_h_

#include "DepSvc1.h"

namespace samples
{
namespace loadorder
{

  //! implementation of DepSvc1 service
  class DepSvc1Impl: public DepSvc1
  {
  public:
    DepSvc1Impl();
    virtual ~DepSvc1Impl();
    virtual void OnCreate();
    virtual void OnFree();
  };
}
}


#endif // _DepSvc1Impl_h_
