// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// DO NOT EDIT
\
#ifneq($(Interface.Namespace.!trim/:/),)

namespace('$(Interface.Namespace.!trim/:/.!dot)');
#ifeqend

(function(){
#ifneq($(Interface.Structs.$Count),0)
///////////////////////////////////////////////////////////////////////////////////////////////////////
// struct serializators
#foreach $(Interface.Structs)
#ifeq($(Struct.Extern),0)
function SerializeStruct_$(Struct.NsName.!trim/:/.!mangle)(tOperation, rstStruct, tNode)
{
#ifneq($(Struct.ParentName),)
  // serialize parent struct
  SerializeStruct_$(Struct.ParentNsName.!trim/:/.!mangle)(tOperation, rstStruct, tNode);

#ifeqend
#foreach $(Struct.Members)
#ifeq($(Param.DataType.Type),struct)
  SerializeStruct_$(Param.DataType.NsName.!trim/:/.!mangle)(tOperation, rstStruct.$(Param.Name), tOperation.AddParameter('$(Param.Name)', '', tNode));
#else
#ifeq($(Param.DataType.Type),typedef)
  SerializeTypedef_$(Param.DataType.NsName.!trim/:/.!mangle)(tOperation, rstStruct.$(Param.Name), tOperation.AddParameter('$(Param.Name)', '', tNode));
#else
#ifeq($(Param.DataType.Type),dataobject)
  rstStruct.$(Param.Name).ToElement(tOperation.AddParameter('$(Param.Name)', null, tNode));
#else
  tOperation.AddParameter('$(Param.Name)', rstStruct.$(Param.Name), tNode);
#ifeqend
#ifeqend
#ifeqend
#end
}

#ifeqend
#end

///////////////////////////////////////////////////////////////////////////////////////////////////////
// struct deserializators
#foreach $(Interface.Structs)
#ifeq($(Struct.Extern),0)
function DeserializeStruct_$(Struct.NsName.!trim/:/.!mangle)(tOperation, tNode)
{
#ifneq($(Struct.ParentName),)
  // deserialize parent struct
  var tResult = DeserializeStruct_$(Struct.ParentNsName.!trim/:/.!mangle)(tOperation, tNode);

#else
  var tResult = {};
#ifeqend
#foreach $(Struct.Members)
#ifeq($(Param.DataType.Type),struct)
  tResult.$(Param.Name) = DeserializeStruct_$(Param.DataType.NsName.!trim/:/.!mangle)(tOperation, tOperation.SubNode('$(Param.Name)', tNode));
#else
#ifeq($(Param.DataType.Type),typedef)
  tResult.$(Param.Name) = DeserializeTypedef_$(Param.DataType.NsName.!trim/:/.!mangle)(tOperation, tOperation.SubNode('$(Param.Name)', tNode));
#else
#ifeq($(Param.DataType.Type),dataobject)
  tResult.$(Param.Name) = new staff.DataObject();
  tResult.$(Param.Name).FromElement(tOperation.SubNode('$(Param.Name)', tNode));
#else
#ifeq($(Param.DataType.Type),string)
  tResult.$(Param.Name) = tOperation.SubNodeText('$(Param.Name)', tNode);
#else
#ifeq($(Param.DataType.Type),generic)
#ifeq($(Param.DataType.Name),byte||int||long||short||unsigned)
  tResult.$(Param.Name) = parseInt(tOperation.SubNodeText('$(Param.Name)', tNode));
#else
#ifeq($(Param.DataType.Name),float||double)
  tResult.$(Param.Name) = parseFloat(tOperation.SubNodeText('$(Param.Name)', tNode));
#else
#ifeq($(Param.DataType.Name),bool)
  tResult.$(Param.Name) = tOperation.SubNodeText('$(Param.Name)', tNode).toLowerCase() in {"1":1, "true":1};
#else
#cgwarning unsupported generic: $(Param.DataType.Name), parsing as string
  tResult.$(Param.Name) = tOperation.SubNodeText('$(Param.Name)', tNode);
#ifeqend
#ifeqend
#ifeqend
#else
#cgerror unsupported type: $(Param.DataType.Type)
#ifeqend
#ifeqend
#ifeqend
#ifeqend
#ifeqend
#end
  return tResult;
}

#ifeqend
#end
//-----------------------------------------------------------------------------------------------------

#ifeqend // ($(Interface.Structs.$Count),0)
#ifneq($(Interface.Typedefs.$Count),0)

///////////////////////////////////////////////////////////////////////////////////////////////////////
// typedef serializators
#foreach $(Interface.Typedefs)
#ifeq($(Typedef.Extern),0)

// $(Typedef.NsName)  Typedef.DataType.Type $(Typedef.DataType.Type) $(Typedef.DataType.NsName)
#ifeq($(Typedef.DataType.IsTemplate),1)
function SerializeTypedef_$(Typedef.NsName.!trim/:/.!mangle)(tOperation, rtType, tNode)
{
#ifeq($(Typedef.DataType.NsName),std::map) // ---- map -------------------------- key
  for(var tKey in rtType)
  {
    var tValue = rtType[tKey];
    if(typeof tValue != 'function')
    {
      var tItem = tOperation.AddParameter('Item', '', tNode);
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Type),struct)    // !!struct!!
      SerializeStruct_$(Typedef.DataType.TemplateParams.TemplateParam1.NsName.!trim/:/.!mangle)(tOperation, tValue, tOperation.AddParameter('Key', '', tItem));
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Type),generic||string)    // !!generic,string!!
      tOperation.AddParameter('Key', tKey, tItem);
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Type),dataobject) // !!dataobject!!
      tOperation.AddDataObjectParameter('Key', tKey, tItem); // dataobject as key??? very strange
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Type),typedef)    // !!typedef!!
      SerializeTypedef_$(Typedef.DataType.TemplateParams.TemplateParam1.NsName.!trim/:/.!mangle)(tOperation, tKey, tOperation.AddParameter('Key', '', tItem));
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Type),template)    // !!template!!
      SerializeTypedef_$(Typedef.DataType.TemplateParams.TemplateParam1.NsName.!trim/:/.!mangle)(tOperation, tKey, tOperation.AddParameter('Key', '', tItem));
#else
#cgerror "Typedef.DataType.Type = $(Typedef.DataType.TemplateParams.TemplateParam1.Type);"
#ifeqend
#ifeqend
#ifeqend
#ifeqend
#ifeqend //  - value -
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam2.Type),struct)    // !!struct!!
      SerializeStruct_$(Typedef.DataType.TemplateParams.TemplateParam2.NsName.!trim/:/.!mangle)(tOperation, tValue, tOperation.AddParameter('Value', '', tItem));
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam2.Type),generic||string)    // !!generic,string!!
      tOperation.AddParameter('Value', tValue, tItem);
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam2.Type),dataobject) // !!dataobject!!
      tOperation.AddDataObjectParameter('Value', tValue, tItem);
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam2.Type),typedef)    // !!typedef!!
      SerializeTypedef_$(Typedef.DataType.TemplateParams.TemplateParam2.NsName.!trim/:/.!mangle)(tOperation, tValue, tOperation.AddParameter('Value', '', tItem));
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam2.Type),template)    // !!template!!
      SerializeTypedef_$(Typedef.DataType.TemplateParams.TemplateParam2.NsName.!trim/:/.!mangle)(tOperation, tValue, tOperation.AddParameter('Value', '', tItem));
#else
#cgerror "Typedef.DataType.Type = $(Typedef.DataType.TemplateParams.TemplateParam2.Type);"
#ifeqend
#ifeqend
#ifeqend
#ifeqend
#ifeqend
    }
  }
#else  // ---------------------------- list -----------------------------------
  for(var i = 0; i != rtType.length; ++i)
  {
// Typedef.DataType.TemplateParams.TemplateParam1.Type = $(Typedef.DataType.TemplateParams.TemplateParam1.Type)
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Type),struct)    // !!struct!!
    SerializeStruct_$(Typedef.DataType.TemplateParams.TemplateParam1.NsName.!trim/:/.!mangle)(tOperation, rtType[i], tOperation.AddParameter('Item', '', tNode));
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Type),generic||string)    // !!generic,string!!
    tOperation.AddParameter('Item', rtType[i], tNode);
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Type),dataobject) // !!dataobject!!
    tOperation.AddDataObjectParameter('Item', rtType[i], tNode);
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Type),typedef)    // !!typedef!!
    SerializeTypedef_$(Typedef.DataType.TemplateParams.TemplateParam1.NsName.!trim/:/.!mangle)(tOperation, rtType[i], tOperation.AddParameter('Item', '', tNode));
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Type),template)    // !!template!!
    SerializeTypedef_$(Typedef.DataType.TemplateParams.TemplateParam1.NsName.!trim/:/.!mangle)(tOperation, rtType[i], tOperation.AddParameter('Item', '', tNode));
#else
#cgerror "Typedef.DataType.Type = $(Typedef.DataType.TemplateParams.TemplateParam1.Type);"
#ifeqend
#ifeqend
#ifeqend
#ifeqend
#ifeqend
  }
#ifeqend // map || list
  return tNode;
}
#else // DataType.IsTemplate
#ifneq($(Typedef.DataType.Type),struct)
function SerializeTypedef_$(Typedef.NsName.!trim/:/.!mangle)(tOperation, rtType, tNode)
{
#ifeq($(Typedef.DataType.Type),generic||string)    // !!generic,string!!
  return tOperation.SetValue(rtType, tNode);
#else
#ifeq($(Typedef.DataType.Type),dataobject) // !!dataobject!!
  return tOperation.SetDataObject(rtType, tNode);
#else
#ifeq($(Typedef.DataType.Type),typedef)    // !!typedef!!
  return SerializeTypedef_$(Typedef.DataType.NsName.!trim/:/.!mangle)(tOperation, rtType, tNode);
#else
#ifeq($(Typedef.DataType.Type),template)    // !!template!!
  return SerializeTypedef_$(Typedef.DataType.NsName.!trim/:/.!mangle)(tOperation, rtType, tNode);
#else
#cgerror "Typedef.DataType.Type = $(Typedef.DataType.Type);"
#ifeqend
#ifeqend
#ifeqend
#ifeqend
}
#ifeqend // #ifneq($(Typedef.DataType.Type),struct)

#ifeqend // ifeq($(Typedef.DataType.IsTemplate),1)
#ifeqend // ifeq not extern
#end // foreach $(Interface.Typedefs)

///////////////////////////////////////////////////////////////////////////////////////////////////////
// typedef deserializators
#foreach $(Interface.Typedefs)
#ifeq($(Typedef.Extern),0)
function DeserializeTypedef_$(Typedef.NsName.!trim/:/.!mangle)(tOperation, tNode)
{
#ifeq($(Typedef.DataType.IsTemplate),1)
// container :: $(Typedef.DataType)
  var tItem = null;

  var tResult = tNode == null ? tOperation.ResultElement() : tNode;
#ifeq($(Typedef.DataType.NsName),std::map)
  var aResult = {};
#else
  var aResult = [];
  var j = 0;
#ifeqend

  for (var i = 0; i < tResult.childNodes.length; i++)
  {
#ifeq($(Typedef.DataType.Type),string)
    aResult[j] = tNode.firstChild != null ? tResult.childNodes[i].firstChild.nodeValue : '';
#else // string
#ifeq($(Typedef.DataType.Type),generic)
    aResult[j] =\
#ifeq($(Typedef.DataType.Name),byte||int||long||short||unsigned)
parseInt(tResult.childNodes[i].firstChild.nodeValue);
#else
#ifeq($(Typedef.DataType.Name),float||double)
parseFloat(tResult.childNodes[i].firstChild.nodeValue);
#else
#ifeq($(Typedef.DataType.Name),bool)
tResult.childNodes[i].firstChild.nodeValue.toLowerCase() in {"1":1, "true":1};
#else
#cgwarning unsupported generic: $(Param.DataType.Name), parsing as string
tResult.childNodes[i].firstChild.nodeValue;
#ifeqend
#ifeqend
#ifeqend
#else // generic
#ifeq($(Typedef.DataType.Type),struct)
// *** struct1 $(Typedef.DataType.NsName)
    aResult[j++] = DeserializeStruct_$(Typedef.DataType.TemplateParams.TemplateParam1.NsName.!trim/:/.!mangle)(tOperation, tResult.childNodes[i]);
#else
#ifeq($(Typedef.DataType.Type),typedef)
// *** td1 $(Typedef.DataType.NsName)
    aResult[j++] = DeserializeTypedef_$(Typedef.DataType.TemplateParams.TemplateParam1.NsName.!trim/:/.!mangle)(tOperation, tResult.childNodes[i]);
#else
#ifeq($(Typedef.DataType.Type),dataobject)
    aResult[j++] = tResult.childNodes[i]; // dataobject 2
#else
#ifeq($(Typedef.DataType.Type),template)  // !!      TEMPLATE        !!
    if (tResult.childNodes[i].nodeName == 'Item')
    {
#ifeq($(Typedef.DataType.NsName),std::map)
//template $(Typedef.DataType.NsName)<$(Typedef.DataType.TemplateParams.TemplateParam1.NsName), $(Typedef.DataType.TemplateParams.TemplateParam2.NsName)>
      var pKeyElem = tOperation.SubNode('Key', tResult.childNodes[i]);
      var pValueElem = tOperation.SubNode('Value', tResult.childNodes[i]);

      var tKey =\
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Type),struct)
 DeserializeStruct_$(Typedef.DataType.TemplateParams.TemplateParam1.NsName.!trim/:/.!mangle)(tOperation, pKeyElem); // *** struct $(Typedef.DataType.TemplateParams.TemplateParam1.NsName)
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Type),typedef)
 DeserializeTypedef_$(Typedef.DataType.TemplateParams.TemplateParam1.NsName.!trim/:/.!mangle)(tOperation, pKeyElem); // *** typedef $(Typedef.DataType.TemplateParams.TemplateParam1.NsName)
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Type),dataobject)
 pKeyElem; // *** dataobject $(Typedef.DataType.TemplateParams.TemplateParam1.NsName)
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Type),string)
 pKeyElem.firstChild != null ? pKeyElem.firstChild.nodeValue : '';
#else // string
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Type),generic)
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Name),byte||int||long||short||unsigned)
 parseInt(pKeyElem.firstChild.nodeValue);
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Name),float||double)
 parseFloat(pKeyElem.firstChild.nodeValue);
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Name),bool)
 pKeyElem.firstChild.nodeValue.toLowerCase() in {"1":1, "true":1};
#else
#cgwarning unsupported generic: $(Typedef.DataType.TemplateParams.TemplateParam1.Name), parsing as string
 pKeyElem.firstChild != null ? pKeyElem.firstChild.nodeValue : '';
#ifeqend
#ifeqend
#ifeqend
#else // generic
#cgerror unsupported type: $(Typedef.DataType.TemplateParams.TemplateParam1.Type)
#ifeqend // generic
#ifeqend // string
#ifeqend // dataobject
#ifeqend // typedef
#ifeqend // struct
      aResult[tKey] =\
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam2.Type),struct)
 DeserializeStruct_$(Typedef.DataType.TemplateParams.TemplateParam2.NsName.!trim/:/.!mangle)(tOperation, pValueElem); // *** struct $(Typedef.DataType.TemplateParams.TemplateParam2.NsName)
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam2.Type),typedef)
 DeserializeTypedef_$(Typedef.DataType.TemplateParams.TemplateParam2.NsName.!trim/:/.!mangle)(tOperation, pValueElem); // *** typedef $(Typedef.DataType.TemplateParams.TemplateParam2.NsName)
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam2.Type),dataobject)
 pValueElem; // *** dataobject $(Typedef.DataType.TemplateParams.TemplateParam2.NsName)
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam2.Type),string)
 pValueElem.firstChild != null ? pValueElem.firstChild.nodeValue : '';
#else // string
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam2.Type),generic)
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam2.Name),byte||int||long||short||unsigned)
 parseInt(pValueElem.firstChild.nodeValue);
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam2.Name),float||double)
 parseFloat(pValueElem.firstChild.nodeValue);
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam2.Name),bool)
 pValueElem.firstChild.nodeValue.toLowerCase() in {"1":1, "true":1};
#else
#cgwarning unsupported generic: $(Typedef.DataType.TemplateParams.TemplateParam2.Name), parsing as string
 pValueElem.firstChild != null ? pValueElem.firstChild.nodeValue : '';
#ifeqend
#ifeqend
#ifeqend
#else
#cgerror unsupported type: $(Typedef.DataType.TemplateParams.TemplateParam2.Type)
#ifeqend // generic
#ifeqend // string
#ifeqend // dataobject
#ifeqend // typedef
#ifeqend // struct
#else                              //   list
//template $(Typedef.DataType.NsName)<$(Typedef.DataType.TemplateParams.TemplateParam1.NsName)>
      aResult[j++] =\
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Type),struct)
 DeserializeStruct_$(Typedef.DataType.TemplateParams.TemplateParam1.NsName.!trim/:/.!mangle)(tOperation, tResult.childNodes[i]); // *** struct $(Typedef.DataType.TemplateParams.TemplateParam1.NsName)
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Type),typedef)
 DeserializeTypedef_$(Typedef.DataType.TemplateParams.TemplateParam1.NsName.!trim/:/.!mangle)(tOperation, tResult.childNodes[i]); // *** typedef $(Typedef.DataType.TemplateParams.TemplateParam1.NsName)
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Type),string)
 tResult.childNodes[i].firstChild != null ? tResult.childNodes[i].firstChild.nodeValue : '';
#else // string
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Type),generic)
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Name),byte||int||long||short||unsigned)
 parseInt(tResult.childNodes[i].firstChild.nodeValue);
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Name),float||double)
 parseFloat(tResult.childNodes[i].firstChild.nodeValue);
#else
#ifeq($(Typedef.DataType.TemplateParams.TemplateParam1.Name),bool)
 tResult.childNodes[i].firstChild.nodeValue.toLowerCase() in {"1":1, "true":1};
#else
#cgwarning unsupported generic: $(Typedef.DataType.TemplateParams.TemplateParam1.Name), parsing as string
 tResult.childNodes[i].firstChild != null ? tResult.childNodes[i].firstChild.nodeValue : '';
#ifeqend
#ifeqend
#ifeqend
#else // generic
#cgerror unsupported type: $(Typedef.DataType.TemplateParams.TemplateParam2.Type)
#ifeqend // generic
#ifeqend // string
#ifeqend // typedef
#ifeqend // struct
#ifeqend // #ifeq($(Typedef.DataType.NsName),std::map)
    }
#else
#cgerror "Typedef.DataType.Type = $(Typedef.DataType.Type);"
#ifeqend
#ifeqend
#ifeqend
#ifeqend
#ifeqend
#ifeqend
  }

  return aResult;
#else // #ifeq($\(Typedef.DataType.IsTemplate),1) --------------------------------------------------------
// not a container :: $(Typedef.DataType.NsName)
  if (tNode == null)
  {
    tNode = tOperation.ResultElement();
  }
#ifeq($(Typedef.DataType.Type),string)    // !!string!!
  return tNode.firstChild != null ? tNode.firstChild.nodeValue : '';
#else // string
#ifeq($(Typedef.DataType.Type),generic)
#ifeq($(Typedef.DataType.Name),byte||int||long||short||unsigned)
  return parseInt(tNode.firstChild.nodeValue);
#else
#ifeq($(Typedef.DataType.Name),float||double)
  return parseFloat(tNode.firstChild.nodeValue);
#else
#ifeq($(Typedef.DataType.Name),bool)
  return tNode.firstChild.nodeValue.toLowerCase() in {"1":1, "true":1};
#else
#cgwarning unsupported generic: $(Param.DataType.Name), parsing as string
  return tNode.firstChild != null ? tNode.firstChild.nodeValue : '';
#ifeqend
#ifeqend
#ifeqend
#else // generic
#ifeq($(Typedef.DataType.Type),dataobject) // !!dataobject!!
  return tNode;
#else
#ifeq($(Typedef.DataType.Type),typedef)    // !!typedef!!
  return DeserializeTypedef_$(Typedef.DataType.NsName.!trim/:/.!mangle)(tOperation, tNode);
#else
#ifeq($(Typedef.DataType.Type),struct)    // !!typedef!!
  return DeserializeTypedef_$(Typedef.DataType.NsName.!trim/:/.!mangle)(tOperation, tNode);
#else
#cgerror unsupported type: $(Typedef.DataType.Type)
#ifeqend
#ifeqend
#ifeqend
#ifeqend
#ifeqend // generic
#ifeqend // string
}

#ifeqend // ifeq not extern
#end

//-----------------------------------------------------------------------------------------------------

#ifeqend // ($(Interface.Typedefs.$Count),0)
#foreach $(Interface.Classes)
///////////////////////////////////////////////////////////////////////////////////
// class: $(Class.ServiceNsName)

$(Class.ServiceNsName) = Class.create();
$(Class.ServiceNsName).prototype =
{
  initialize: function(sServiceUri, sSessionId, sInstanceId, sTargetNamespace)
  {
    if (!sServiceUri)
    {
      sServiceUri = webapp.Env.protocol + webapp.Session.sHost + (webapp.Session.sPort ? (':' + webapp.Session.sPort) : '') + '/axis2/services/$(Class.ServiceNsName)';
    }

    if (!sTargetNamespace)
    {
      sTargetNamespace = \
#ifneq($(Interface.TargetNamespace),||http://tempui.org/$(Class.ServiceNsName))
'$(Interface.TargetNamespace)';
#else
sServiceUri;
#ifeqend
    }

    this.sTargetNamespace = sTargetNamespace || sServiceUri;

    this.tClient = new staff.Client(sServiceUri, sSessionId || webapp.Session.sId || '', sInstanceId);
  },

  destroy: function()
  {
    this.tClient && this.tClient.destroy();
  },

  SetDataObjectAsXml: function(bDataObjectAsXml)
  {
    this.bDataObjectAsXml = bDataObjectAsXml;
  },

  SetID: function(sSessionId)
  {
    this.tClient.SetSessionId(sSessionId);
  }\
#foreach $(Class.Members)
,

  $(Member.Name): function(\
#foreach $(Member.Params)
$(Param.Name), \
#end
pOnComplete, pOnError)
  {
    var tOperation = new staff.Operation('$(Member.Name)', this.sTargetNamespace, '\
#ifneq($(Member.Return.ResponseName),$(Member.Name)Result)
$(Member.Return.ResponseName)\
#ifeqend
', '$(Member.Return.NodeName)');

#ifneq($(Member.Options.*soapAction),||$(Class.ServiceName)#$(Member.Name))
    tOperation.SetSoapAction('$(Member.Options.*soapAction)');

#ifeqend
#foreach $(Member.Params)
#ifeq($(Param.DataType.Type),struct) // !!struct!!
    SerializeStruct_$(Param.DataType.NsName.!trim/:/.!mangle)(tOperation, $(Param.Name), tOperation.AddParameter('$(Param.Name)'));
#else
#ifeq($(Param.DataType.Type),typedef)    // !!typedef!!
    SerializeTypedef_$(Param.DataType.NsName.!trim/:/.!mangle)(tOperation, $(Param.Name), tOperation.AddParameter('$(Param.Name)'));
#else
#ifeq($(Param.DataType.Type),generic||string)    // !!generic,string!!
    tOperation.AddParameter('$(Param.Name)', $(Param.Name));
#else
#ifeq($(Param.DataType.Type),dataobject) // !!dataobject!!
    if (!this.bDataObjectAsXml)
    {
      tOperation.AddDataObjectParameter('$(Param.Name)', $(Param.Name));
    }
    else
    {
      tOperation.AddXmlParameter('$(Param.Name)', $(Param.Name));
    }
#else
#cgerror "Error param: $(Param.DataType.Type)"
#ifeqend
#ifeqend
#ifeqend
#ifeqend
#end
    if(typeof pOnComplete == 'function')
    { // make async call
#ifeq($(Member.Return.Type),dataobject) // !!dataobject!!
      var bDataObjectAsXml = this.bDataObjectAsXml;
#ifeqend
      this.tClient.InvokeOperation(tOperation,
        function(tOperation)
        {
#ifeq($(Member.Return.Type),struct) // !!struct!!
          pOnComplete(DeserializeStruct_$(Member.Return.NsName.!trim/:/.!mangle)(tOperation), tOperation);
#else
#ifeq($(Member.Return.Type),typedef)    // !!typedef!!
          pOnComplete(DeserializeTypedef_$(Member.Return.NsName.!trim/:/.!mangle)(tOperation), tOperation);
#else
#ifeq($(Member.Return.Type),dataobject) // !!dataobject!!
          if (!bDataObjectAsXml)
          {
            pOnComplete(new staff.DataObject(tOperation.ResultElement().firstChild), tOperation);
          }
          else
          {
            pOnComplete(tOperation.ResultElement().firstChild, tOperation);
          }
#else
#ifeq($(Member.Return.Type),generic)    // !!generic!!
#ifneq($(Member.Return.Name),void)      // !!not_void!!
          pOnComplete(\
#ifeq($(Member.Return.Name),byte||int||long||short||unsigned)
parseInt(tOperation.ResultValue())\
#else
#ifeq($(Member.Return.Name),float||double)
parseFloat(tOperation.ResultValue())\
#else
#ifeq($(Member.Return.Name),bool)
tOperation.ResultValue().toLowerCase() in {"1":1, "true":1}\
#else
#cgwarning unsupported generic: $(Param.DataType.Name), parsing as string
tOperation.ResultValue()\
#ifeqend
#ifeqend
#ifeqend
, tOperation);
#else                                   // !!void!!
          pOnComplete(tOperation);
#ifeqend
#else
#ifeq($(Member.Return.Type),string)    // !!string!!
          pOnComplete(tOperation.ResultValue(), tOperation);
#else
#cgerror "Error result: $(Param.DataType.Type)"
#ifeqend
#ifeqend
#ifeqend
#ifeqend
#ifeqend
        },
        pOnError
      );
    }
    else
    {
      this.tClient.InvokeOperation(tOperation);
#ifeq($(Member.Return.Type),struct) // !!struct!!

      return DeserializeStruct_$(Member.Return.NsName.!trim/:/.!mangle)(tOperation);
#else // end struct
#ifeq($(Member.Return.Type),typedef)    // !!typedef!!

      return DeserializeTypedef_$(Member.Return.NsName.!trim/:/.!mangle)(tOperation);
#else // end typedef
#ifeq($(Member.Return.Type),dataobject) // !!dataobject!!

    if (!this.bDataObjectAsXml)
    {
      return new staff.DataObject(tOperation.ResultElement().firstChild);
    }
    else
    {
      return tOperation.ResultElement().firstChild;
    }
#else // end dataobject
#ifeq($(Member.Return.Type),generic)    // !!generic!!
#ifneq($(Member.Return.Name),void)      // !!not_void!!

      return \
#ifeq($(Member.Return.Name),byte||int||long||short||unsigned)
parseInt(tOperation.ResultValue());
#else
#ifeq($(Member.Return.Name),float||double)
parseFloat(tOperation.ResultValue());
#else
#ifeq($(Member.Return.Name),bool)
tOperation.ResultValue().toLowerCase() in {"1":1, "true":1};
#else
#cgwarning unsupported generic: $(Param.DataType.Name), parsing as string
tOperation.ResultValue();
#ifeqend
#ifeqend
#ifeqend
#ifeqend // not void
#else // end generic
#ifeq($(Member.Return.Type),string)    // !!string!!
      return tOperation.ResultValue();
#else // end string
#cgerror "Error return: $(Param.DataType.Type)"
#ifeqend
#ifeqend
#ifeqend
#ifeqend
#ifeqend
    }
  }\
#end

}

#end // Interface.Classes

})();
