/*
 *  Copyright 2009 Utkin Dmitry
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/* 
 *  This file is part of the WSF Staff project.
 *  Please, visit http://code.google.com/p/staff for more information.
 */

// This file generated by staff_codegen
// Service Implementation

#ifndef _LoginImpl_h_
#define _LoginImpl_h_

#include "Login.h"

namespace staff
{
  class LoginImpl: public Login
  {
  public:
    virtual ~LoginImpl();
    virtual std::string LoginUser(const std::string& sUserName, const std::string& sPassword);
    virtual std::string OpenSession(const std::string& sUserName, const std::string& sPassword, bool bCloseExisting);
    virtual void Logout();
    virtual int KeepAliveSession();
    virtual int GetUserId();
    virtual std::string GetUserName();
    virtual std::string GetUserDescription();
    virtual int GetSessionExpiration() const;
    virtual bool ValidateSession();
    virtual int GetSessionExpiresIn() const;
  };
}


#endif // _LoginImpl_h_
