/*
 *  Copyright 2009 Utkin Dmitry
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/* 
 *  This file is part of the WSF Staff project.
 *  Please, visit http://code.google.com/p/staff for more information.
 */

// This file generated by staff_codegen
// Service Implementation

#include <staff/common/Exception.h>
#include <rise/common/exmacros.h>
#include <rise/common/ExceptionTemplate.h>
#include <staff/security/Sessions.h>
#include "LoginContext.h"
#include "LoginImpl.h"

namespace staff
{

  CLoginImpl::~CLoginImpl()
  {
  }

  std::string CLoginImpl::Login(const std::string& sUserName, const std::string& sPassword)
  {
    return OpenSession(sUserName, sPassword, true);
  }

  std::string CLoginImpl::OpenSession(const std::string& sUserName, const std::string& sPassword, bool bCloseExisting)
  {
    std::string tResult;

    RISE_ASSERTES(GetSessionID() == staff::security::CSessions::sNobodySessionId,
      rise::CLogicAlreadyExistsException, "Cannot login from non-nobody session");

    staff::security::CSessions::Inst().Open(sUserName, sPassword, bCloseExisting, tResult);

    return tResult;  // result
  }

  std::string CLoginImpl::OpenExtraSession(int nExtraSessionId)
  {
    std::string tResult;

    staff::security::CSessions::Inst().OpenExtra(GetSessionID(), nExtraSessionId, tResult);

    return tResult;  // result
  }

  void CLoginImpl::CloseExtraSession(int nExtraSessionId)
  {
    staff::security::CSessions::Inst().CloseExtra(GetSessionID(), nExtraSessionId);
  }

  void CLoginImpl::Logout()
  {
    staff::security::CSessions::Inst().Close(GetSessionID());
  }

  void CLoginImpl::KeepAliveSession()
  {
    staff::security::CSessions::Inst().Keepalive(GetSessionID());
  }

  std::string CLoginImpl::GetUserName()
  {
    std::string tResult;

    staff::security::CSessions::Inst().GetUserName(GetSessionID(), tResult);

    return tResult;  // result
  }

  int CLoginImpl::GetSessionExpiration() const
  {
    return staff::security::CSessions::Inst().GetExpiration();
  }

  bool CLoginImpl::ValidateSession()
  {
    return staff::security::CSessions::Inst().Validate(GetSessionID());
  }

  const std::string& CLoginImpl::GetSessionID()
  {
    if(m_sSessionId.size() == 0)
    {
      m_sSessionId = CLoginContext::GetContext().GetServiceID(this);
    }
    return m_sSessionId;
  }

}

