// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// Client skeleton

#include <memory>
#include <staff/utils/Log.h>
#include <staff/common/Exception.h>
#include <staff/client/ServiceFactory.h>
#include "Transport.h"
#include "Transport2.h"

// callbacks

int main(int /*nArgs*/, const char* /*paszArgs*/[])
{
  try
  {
    std::auto_ptr< ::samples::abstract::Transport > pTransport(::staff::ServiceFactory::Inst().GetService< ::samples::abstract::Transport >());

    STAFF_ASSERT(pTransport.get(), "Cannot get client for service samples.abstract.Transport!");

    // Invoke Your service here:
    {
      ::samples::abstract::TransportInfo tTransportCar = pTransport->GetTransport(samples::abstract::TransportTypeCar);
      staff::LogInfo() << "Resulting type = " << tTransportCar.tpVehicle.GetType();
      const samples::abstract::Car& rCar = dynamic_cast<const samples::abstract::Car&>(*tTransportCar.tpVehicle);
      staff::LogInfo() << "Get car. model = " << rCar.sModel;
    }

    {
      ::samples::abstract::TransportInfo tTransportPlane = pTransport->GetTransport(samples::abstract::TransportTypePlane);
      staff::LogInfo() << "Resulting type = " << tTransportPlane.tpVehicle.GetType();
      const samples::abstract::Plane& rPlane = dynamic_cast<const samples::abstract::Plane&>(*tTransportPlane.tpVehicle);
      staff::LogInfo() << "Get Plane. number = " << rPlane.sSerialNumber;
    }

    {
      staff::Abstract<samples::abstract::Vehicle> tpReq(new samples::abstract::Plane);
      samples::abstract::Plane& rPlaneReq = static_cast<samples::abstract::Plane&>(*tpReq);
      rPlaneReq.sSerialNumber = "1111";

      staff::Abstract<samples::abstract::Vehicle> tPlaneResult = pTransport->Echo(tpReq);
      const samples::abstract::Plane& rPlaneRes = dynamic_cast<const samples::abstract::Plane&>(*tPlaneResult);
      staff::LogInfo() << "echo. number = " << rPlaneRes.sSerialNumber;
    }

    {
      staff::Abstract<samples::abstract::Vehicle> tpReq(new samples::abstract::Submarine);
      samples::abstract::Submarine& rSubmarineReq = static_cast<samples::abstract::Submarine&>(*tpReq);
      rSubmarineReq.sOtherInfo = "some info";

      staff::Abstract<samples::abstract::Vehicle> tSubmarineResult = pTransport->Echo(tpReq);
      const samples::abstract::Submarine& rSubmarineRes = dynamic_cast<const samples::abstract::Submarine&>(*tSubmarineResult);
      staff::LogInfo() << "echo. other info = " << rSubmarineRes.sOtherInfo;
    }

  }
  STAFF_CATCH_ALL

  return 0;
}

